[env]
platform = espressif32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
	m5stack/M5Unified
	m5stack/M5CoreS3
	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
	bblanchon/ArduinoJson @ ^7.0.4
	adafruit/Adafruit BME680 Library @ ^2.0.4
	adafruit/Adafruit Unified Sensor @ ^1.1.14
	madhephaestus/ESP32Servo @ ^3.0.5
	earlephilhower/ESP8266SAM

[env:m5stack-cores3]
board = m5stack-cores3
board_build.arduino.memory_type = qio_opi
lib_extra_dirs = ../shared/lib
build_flags = -I include 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
