[env]
platform = espressif32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
	m5stack/M5Unified
	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
	bblanchon/ArduinoJson @ ^7.0.4
	adafruit/Adafruit BME680 Library @ ^2.0.4
	adafruit/Adafruit Unified Sensor @ ^1.1.14

[env:m5stack-cores3]
board = m5stack-cores3

[env:m5stack-core2]
board = m5stack-core2

[env:m5stick-c]
board = m5stick-c
