#pragma once
#include <Arduino.h>

const char index_html[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>BuddyBotM5 Control Panel</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/nipplejs/0.10.1/nipplejs.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Rajdhani:wght@500;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="hud-container">
        <header class="glass-panel">
            <h1>BUDDY_BOT // M5</h1>
            <div class="status-indicator">
                <span id="conn-status" class="offline">OFFLINE</span>
            </div>
        </header>

        <main>
            <!-- Camera Feed Section -->
            <section class="glass-panel cam-section">
                <div class="cam-frame">
                    <!-- The IP of the ATOM S3R CAM will go here -->
                    <img id="cam-stream" src="" alt="NO SIGNAL" />
                    <div class="cam-overlay">
                        <div class="crosshair"></div>
                    </div>
                </div>
            </section>

            <div class="controls-wrapper">
                <!-- Movement Joystick -->
                <section class="glass-panel drive-section">
                    <h2>DRIVE SYS</h2>
                    <div id="joystick-zone"></div>
                </section>

                <!-- BME680 Telemetry -->
                <section class="glass-panel telemetry-section">
                    <h2>TELEMETRY</h2>
                    <div class="telemetry-grid">
                        <div class="data-box">
                            <span class="label">TEMP</span>
                            <span class="value" id="val-temp">--°C</span>
                        </div>
                        <div class="data-box">
                            <span class="label">HUM</span>
                            <span class="value" id="val-hum">--%</span>
                        </div>
                        <div class="data-box">
                            <span class="label">PRES</span>
                            <span class="value" id="val-pres">--hPa</span>
                        </div>
                        <div class="data-box">
                            <span class="label">GAS</span>
                            <span class="value" id="val-gas">--KΩ</span>
                        </div>
                        <div class="data-box">
                            <span class="label">ROLL</span>
                            <span class="value" id="val-roll">--°</span>
                        </div>
                        <div class="data-box">
                            <span class="label">PITCH</span>
                            <span class="value" id="val-pitch">--°</span>
                        </div>
                    </div>
                </section>
            </div>

            <!-- Emotion Panel -->
            <section class="glass-panel emotion-section">
                <h2>PERSONA CONTROLS</h2>
                <div class="emotion-grid">
                    <button class="emotion-btn" data-emotion="0">😐 NEUTRAL</button>
                    <button class="emotion-btn" data-emotion="1">😃 HAPPY</button>
                    <button class="emotion-btn" data-emotion="2">😡 ANGRY</button>
                    <button class="emotion-btn" data-emotion="3">😴 SLEEPY</button>
                </div>
            </section>

            <!-- 8 Servos Panel -->
            <section class="glass-panel servos-section">
                <h2>SERVO ARRAY</h2>
                <div class="sliders-grid">
                    <!-- Generated by JS -->
                </div>
            </section>
        </main>
    </div>
    <script src="app.js"></script>
</body>
</html>

)rawliteral";

const char style_css[] PROGMEM = R"rawliteral(
:root {
    --bg-color: #050a0f;
    --glass-bg: rgba(10, 25, 45, 0.6);
    --glass-border: rgba(0, 255, 255, 0.2);
    --accent-cyan: #00f3ff;
    --accent-magenta: #ff00ea;
    --text-main: #e0f7fa;
    --font-heading: 'Orbitron', sans-serif;
    --font-body: 'Rajdhani', sans-serif;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    user-select: none;
}

body {
    background-color: var(--bg-color);
    background-image: 
        linear-gradient(rgba(0, 255, 255, 0.05) 1px, transparent 1px),
        linear-gradient(90deg, rgba(0, 255, 255, 0.05) 1px, transparent 1px);
    background-size: 30px 30px;
    color: var(--text-main);
    font-family: var(--font-body);
    height: 100vh;
    width: 100vw;
    overflow-x: hidden;
    padding: 10px;
}

.hud-container {
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: 15px;
}

.glass-panel {
    background: var(--glass-bg);
    backdrop-filter: blur(10px);
    border: 1px solid var(--glass-border);
    border-radius: 12px;
    padding: 15px;
    box-shadow: 0 0 20px rgba(0, 255, 255, 0.05);
}

header {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

header h1 {
    font-family: var(--font-heading);
    font-size: 1.5rem;
    color: var(--accent-cyan);
    text-shadow: 0 0 10px var(--accent-cyan);
    letter-spacing: 2px;
}

.status-indicator span {
    font-weight: bold;
    padding: 5px 10px;
    border-radius: 4px;
    font-size: 1rem;
}

.offline { color: #ff3333; box-shadow: 0 0 10px #ff3333; }
.online { color: #33ff33; box-shadow: 0 0 10px #33ff33; }

h2 {
    font-family: var(--font-heading);
    font-size: 1rem;
    color: var(--accent-magenta);
    margin-bottom: 10px;
    text-shadow: 0 0 5px var(--accent-magenta);
}

.cam-frame {
    width: 100%;
    aspect-ratio: 16/9;
    background: #000;
    border-radius: 8px;
    position: relative;
    overflow: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
}

#cam-stream {
    width: 100%;
    height: 100%;
    object-fit: cover;
}

.cam-overlay {
    position: absolute;
    inset: 0;
    pointer-events: none;
    border: 2px solid rgba(0, 255, 255, 0.3);
}

.crosshair {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 40px;
    height: 40px;
    border: 1px solid var(--accent-cyan);
    border-radius: 50%;
}
.crosshair::before, .crosshair::after {
    content: '';
    position: absolute;
    background: var(--accent-cyan);
}
.crosshair::before { top: 50%; left: -10px; right: -10px; height: 1px; }
.crosshair::after { left: 50%; top: -10px; bottom: -10px; width: 1px; }

.controls-wrapper {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 15px;
}

@media (max-width: 768px) {
    .controls-wrapper { grid-template-columns: 1fr; }
}

#joystick-zone {
    width: 100%;
    height: 200px;
    position: relative;
    background: radial-gradient(circle, rgba(0,243,255,0.1) 0%, transparent 70%);
    border-radius: 8px;
}

.telemetry-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
    height: calc(100% - 30px);
}

.data-box {
    background: rgba(0, 0, 0, 0.4);
    border: 1px solid var(--glass-border);
    border-radius: 6px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 10px;
}

.data-box .label {
    font-size: 0.8rem;
    color: #888;
    letter-spacing: 1px;
}

.data-box .value {
    font-size: 1.5rem;
    font-weight: bold;
    color: var(--accent-cyan);
}

.sliders-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
    gap: 15px;
}

.slider-container {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.slider-container label {
    font-size: 0.9rem;
    margin-bottom: 5px;
}

input[type=range] {
    -webkit-appearance: none;
    width: 100%;
    background: transparent;
}
input[type=range]::-webkit-slider-thumb {
    -webkit-appearance: none;
    height: 20px;
    width: 10px;
    background: var(--accent-magenta);
    cursor: pointer;
    box-shadow: 0 0 10px var(--accent-magenta);
}
input[type=range]::-webkit-slider-runnable-track {
    width: 100%;
    height: 4px;
    cursor: pointer;
    background: rgba(0, 255, 255, 0.3);
}

.emotion-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 10px;
}

.emotion-btn {
    background: rgba(0, 255, 255, 0.1);
    border: 1px solid var(--accent-cyan);
    color: var(--text-main);
    padding: 10px;
    border-radius: 6px;
    cursor: pointer;
    font-family: var(--font-heading);
    transition: all 0.2s;
}

.emotion-btn:active, .emotion-btn:hover {
    background: var(--accent-cyan);
    color: #000;
}

)rawliteral";

const char app_js[] PROGMEM = R"rawliteral(
document.addEventListener('DOMContentLoaded', () => {
    // 1. Setup Joystick
    const joystickZone = document.getElementById('joystick-zone');
    const manager = nipplejs.create({
        zone: joystickZone,
        mode: 'static',
        position: { left: '50%', top: '50%' },
        color: '#00f3ff'
    });

    let motorTimer = null;
    let currentSpeed = 0;
    let currentTurn = 0;

    manager.on('move', (evt, data) => {
        const force = Math.min(data.force, 1);
        const angle = data.angle.radian;
        
        // Convert to speed and turn
        // Math.sin(angle) goes from 1 (up) to -1 (down)
        // Math.cos(angle) goes from 1 (right) to -1 (left)
        currentSpeed = Math.sin(angle) * force * 100; // -100 to 100
        currentTurn = Math.cos(angle) * force * 100; // -100 to 100
    });

    manager.on('end', () => {
        currentSpeed = 0;
        currentTurn = 0;
        sendMotorCommand(0, 0);
    });

    // Send motor commands periodically if active
    setInterval(() => {
        if (currentSpeed !== 0 || currentTurn !== 0) {
            sendMotorCommand(currentSpeed, currentTurn);
        }
    }, 100);

    function sendMotorCommand(speed, turn) {
        // Send speed and turn directly to backend
        // The ESP32 will handle differential mix and caster servo logic
        fetch('/api/motors', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ speed: Math.round(speed), turn: Math.round(turn) })
        }).catch(err => console.error("Motor API Error:", err));
    }

    // 2. Setup Servos
    const slidersGrid = document.querySelector('.sliders-grid');
    for (let i = 0; i < 8; i++) {
        const container = document.createElement('div');
        container.className = 'slider-container';
        
        const label = document.createElement('label');
        label.innerText = `CH ${i}`;
        
        const input = document.createElement('input');
        input.type = 'range';
        input.min = '0';
        input.max = '180';
        input.value = '90';
        input.dataset.channel = i;

        input.addEventListener('change', (e) => {
            const ch = e.target.dataset.channel;
            const val = e.target.value;
            fetch('/api/servo', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ channel: parseInt(ch), angle: parseInt(val) })
            });
        });

        container.appendChild(label);
        container.appendChild(input);
        slidersGrid.appendChild(container);
    }

    // 3. Telemetry Polling
    setInterval(() => {
        fetch('/api/telemetry')
            .then(res => res.json())
            .then(data => {
                document.getElementById('val-temp').innerText = data.temp.toFixed(1) + '°C';
                document.getElementById('val-hum').innerText = data.hum.toFixed(1) + '%';
                document.getElementById('val-pres').innerText = data.pres.toFixed(0) + 'hPa';
                document.getElementById('val-gas').innerText = (data.gas / 1000).toFixed(1) + 'KΩ';
                
                if (data.roll !== undefined) document.getElementById('val-roll').innerText = data.roll.toFixed(1) + '°';
                if (data.pitch !== undefined) document.getElementById('val-pitch').innerText = data.pitch.toFixed(1) + '°';
                
                document.getElementById('conn-status').innerText = 'ONLINE';
                document.getElementById('conn-status').className = 'online';
            })
            .catch(err => {
                document.getElementById('conn-status').innerText = 'OFFLINE';
                document.getElementById('conn-status').className = 'offline';
            });
    }, 2000);

    // 4. Set Camera Stream IP
    // Assume cam is reachable via /cam-stream endpoint proxy, or specific IP
    // For now we'll fetch its IP from a config endpoint
    fetch('/api/config')
        .then(res => res.json())
        .then(data => {
            if (data.cam_ip) {
                document.getElementById('cam-stream').src = `http://${data.cam_ip}:81/stream`;
            }
        });

    // 5. Persona Emotion Buttons
    document.querySelectorAll('.emotion-btn').forEach(btn => {
        btn.addEventListener('click', (e) => {
            const emotion = e.target.dataset.emotion;
            fetch('/api/persona', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ emotion: parseInt(emotion) })
            });
        });
    });
});

)rawliteral";

